import "./reset.css";
import "./globals.css";
import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <h2>To Do List</h2>
        </header>
        <main>{children}</main>
        <footer className={styles.footer}>made by kimkyeongbeom4844</footer>
      </body>
    </html>
  );
};
export default RootLayout;
